---
- name: "Install the hosts file"
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - git
      - fakeroot
      - ncurses-dev
      - xz-utils
      - libssl-dev
      - bc
      - flex
      - libelf-dev
      - bison
    name: build-essential
    update_cache: yes
  become: yes

# - name: Install clang
#   ansible.builtin.apt:
#     name: clang
#     update_cache: yes
#   become: yes

- name: Get Rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    chmod +x rustup.sh
    ./rustup.sh -y

- name: Remove rustup script
  ansible.builtin.file:
    path: rustup.sh
    state: absent

- name: Install Rust Bindgen
  ansible.builtin.shell: |
    . .cargo/env
    cargo install --git https://github.com/rust-lang/rust-bindgen --tag v0.65.1 bindgen-cli
- name: Downgrade rust to kernel supported version
  ansible.builtin.shell: |
    . .cargo/env
    cd /vagrant/linux-rust
    rustup override set $(scripts/min-tool-version.sh rustc)

- name: Add rust src component
  ansible.builtin.shell: |
    . .cargo/env
    rustup component add rust-src

- name: Install the latest kernel version
  ansible.builtin.shell: |
    cd /vagrant/linux-rust
    sudo make modules_install && sudo make install

- name: Reload the VM
  ansible.builtin.reboot:
