---
- name: "Install the hosts file"
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - git
      - fakeroot
      - ncurses-dev
      - xz-utils
      - libssl-dev
      - bc
      - flex
      - libelf-dev
      - bison
    name: build-essential
    update_cache: yes
  become: yes

# - name: Install clang
#   ansible.builtin.apt:
#     name: clang
#     update_cache: yes
#   become: yes

- name: Get Rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    chmod +x rustup.sh
    ./rustup.sh -y

- name: Remove rustup script
  ansible.builtin.file:
    path: rustup.sh
    state: absent

- name: Download Linux Kernel 6.2.7
  ansible.builtin.get_url:
    url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.2.7.tar.xz
    dest: /vagrant/

- name: Extract linux source
  ansible.builtin.unarchive:
    src: /vagrant/linux-6.2.7.tar.xz
    dest: /vagrant
    remote_src: yes

- name: downgrade rust to kernel supported version
  ansible.builtin.shell: |
    . .cargo/env
    cd /vagrant/linux-6.2.7
    rustup override set $(scripts/min-tool-version.sh rustc)

- name: add std library source (Rustforkernel requirement)
  ansible.builtin.shell: |
    . .cargo/env
    rustup component add rust-src

- name: install bindgen (Rustforkernel requirement)
  ansible.builtin.shell: |
    . .cargo/env
    cd /vagrant/linux-6.2.7
    cargo install --locked --version $(scripts/min-tool-version.sh bindgen) bindgen


  
  

